---
- name: Deploy Spring Petclinic
  hosts: prod
  become: yes
  tasks:
    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Copy Petclinic war file
      copy:
        src: ./spring-petclinic/target/spring-petclinic.war
        dest: /opt/spring-petclinic.war

    - name: Run Spring PetClinic
      shell: nohup java -jar /opt/spring-petclinic.war > /opt/petclinic.log 2>&1 &