---
- name: Deploy Spring Petclinic
  hosts: prod
  become: yes
  tasks:
    - name: Install Java 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes

    - name: Copy Petclinic JAR file
      copy:
        src: files/spring-petclinic-*.jar
        dest: /opt/spring-petclinic.jar

    - name: Stop existing Spring Petclinic instance (if any)
      shell: pkill -f 'java -jar /opt/spring-petclinic.jar'
      ignore_errors: yes

    - name: Run Spring PetClinic
      shell: nohup java -jar /opt/spring-petclinic.jar > /opt/petclinic.log 2>&1 &


