---
- name: Teardown Spring Petclinic
  hosts: prod
  become: yes
  tasks:
    - name: Kill any running Petclinic process
      shell: pkill -f 'java -jar /opt/spring-petclinic.jar'
      ignore_errors: yes